workspace:
  base: /go
  path: src/github.com/astronomer/astro-cli

pipeline:
  # Build binary
  build:
    image: golang:1.12.5
    commands:
      - go version
      - make build

  # Test the code
  test:
    image: asoldatenko/dnd-golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make test

  # Cut releases with goreleaser when tagged
  push:
    image: goreleaser/goreleaser:v0.106
    secrets: [ github_token ]
    commands:
      - git fetch --no-tags origin +refs/tags/${DRONE_TAG}:refs/tags/${DRONE_TAG}
      - goreleaser release --rm-dist
    when:
      event: tag

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: platform
    when:
      status: [ failure ]
